# Generated by Django 4.1 on 2022-09-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField()),
                ('boards_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='boards.boards')),
            ],
        ),
    ]
