# Generated by Django 4.1 on 2022-09-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('expirate_date', models.DateField()),
                ('position', models.PositiveIntegerField()),
                ('lists_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Card', to='lists.lists')),
            ],
        ),
    ]
